api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    collection:
            # The default order of results.
            order: 'ASC'

            # The name of the query parameter to order results.
            order_parameter_name: 'order'

            pagination:
                # To enable or disable pagination for all resource collections by default.
                enabled: true
                items_per_page_parameter_name: itemsPerPage # Default value

                # The default number of items per page.
               # items_per_page: 100

               # To allow the client to set the number of items per page.
                client_items_per_page: true

                # To allow the client to enable or disable the pagination.
                client_enabled: true

               
                # Page parameter name
                page_parameter_name: _page


